### ISSUE TITLE
Really confused about where can I get output pics

### ISSUE THREAD

**Issue by Saafo** [BlueCocoa/waifu2x-ncnn-vulkan-macos#3]
I can't find out how to save the output pictures....

**Comment by Saafo** [comment]
I see... They're where they came from...

**Comment by BlueCocoa** [comment]
Hi, I've added usage in the [usage section](https://github.com/BlueCocoa/waifu2x-ncnn-vulkan-macos#usage) under README.md, hope that can provide some useful information about this issue.

**Comment by Saafo** [comment]
Thanks~
